"use client";

import { Suspense } from "react";
import { useParams, useSearchParams } from "next/navigation";
import { useQuery } from "convex/react";
import { api } from "@fammycomforts/backend/convex/_generated/api";
import { formatKes } from "@/lib/money";

/**
 * Printable invoice/receipt (Story 5.6). Access is verified exactly like the
 * portal (reference + contact in the query string); amounts are the ledger
 * snapshot taken at generation time. "PDF" = browser print-to-PDF of this
 * print-optimized document (server-side rendering deferred — documented).
 */
function InvoiceDoc() {
  const { invoiceId } = useParams<{ orgSlug: string; invoiceId: string }>();
  const sp = useSearchParams();
  const reference = sp.get("ref") ?? "";
  const contact = sp.get("contact") ?? "";

  const portal = useQuery(
    api.guestBookings.portal,
    reference && contact ? { reference, contact } : "skip",
  );

  if (!reference || !contact) {
    return <p className="p-8 text-sm">Open this document from your booking portal.</p>;
  }
  if (portal === undefined) return <p className="p-8 text-sm">Loading…</p>;
  const invoice = portal?.invoices.find((i) => i.invoiceId === invoiceId);
  if (!portal || !invoice) return <p className="p-8 text-sm">Document not found.</p>;

  return (
    <main className="print-doc mx-auto max-w-xl space-y-6 bg-white p-8 text-black print:p-0">
      <header className="flex items-start justify-between border-b pb-4">
        <div>
          <h1 className="text-xl font-semibold">{portal.propertyName}</h1>
          <p className="text-sm">{invoice.isReceipt ? "Receipt" : "Invoice"}</p>
        </div>
        <div className="text-right text-sm">
          <p className="font-mono font-semibold">{invoice.number}</p>
          <p>Booking {portal.reference}</p>
        </div>
      </header>

      <section className="text-sm">
        <p>Guest: {portal.guestName}</p>
        <p>
          Stay: {portal.checkInDate} → {portal.checkOutDate} · {portal.roomType} · Room{" "}
          {portal.roomNumber}
        </p>
      </section>

      <table className="w-full text-sm">
        <thead>
          <tr className="border-b text-left">
            <th className="py-1">Description</th>
            <th className="py-1 text-right">Amount</th>
          </tr>
        </thead>
        <tbody>
          {invoice.lines.map((line, i) => (
            <tr key={i} className="border-b border-dashed">
              <td className="py-1">{line.description}</td>
              <td className="py-1 text-right">{formatKes(line.amountCents)}</td>
            </tr>
          ))}
          <tr className="font-semibold">
            <td className="py-2">Total</td>
            <td className="py-2 text-right">{formatKes(invoice.totalCents)}</td>
          </tr>
        </tbody>
      </table>

      <footer className="flex items-center justify-between text-xs text-neutral-600">
        <span>Generated by Fammy Comforts.</span>
        <button className="underline print:hidden" onClick={() => window.print()}>
          Print / save as PDF
        </button>
      </footer>
    </main>
  );
}

export default function InvoicePage() {
  return (
    <Suspense fallback={null}>
      <InvoiceDoc />
    </Suspense>
  );
}
